#!/usr/bin/env python3
"""Emit factlockcam_app/dart_defines.json and generated_dart_defines.dart.

Only keys required by `AppConfig` are written so secrets from `.env.local`
(e.g. SUPABASE_DB_PASSWORD) are never embedded in the compiled app.

The Dart file supplies `String.fromEnvironment(..., defaultValue: ...)` fallbacks
so plain `flutter run` (without `--dart-define-from-file`) still picks up
`.env.local` after `scripts/sync_flutter_dart_defines.sh`.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

REQUIRED_KEYS = ("SUPABASE_URL", "SUPABASE_ANON_KEY")
OPTIONAL_KEYS = (
    "LOCAL_ANON_KEY",
    "WEB_BASE_URL",
    "WEB_ARCHIVE_BASE_URL",
    "APP_ENVIRONMENT",
    "SUPPORT_URL",
    "USE_POLYGON_NOTARIZER",
    "POLYGON_RPC_URL",
)
ALLOWED_KEYS = REQUIRED_KEYS + OPTIONAL_KEYS


def _normalize_https_dup_scheme(url: str) -> str:
    """Fix copy-paste errors like ``https://https://project.supabase.com``."""
    v = url.strip()
    while v.startswith("https://https://"):
        v = "https://" + v.removeprefix("https://https://")
    if v.startswith("http://https://"):
        v = "https://" + v.removeprefix("http://https://")
    return v


def parse_env_file(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    text = path.read_text(encoding="utf-8")
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].strip()
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2)
        if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
            val = val[1:-1]
        out[key] = val
    return out


def resolve_values(env_file: Path | None, existing_out: Path | None = None) -> dict[str, str]:
    file_vals: dict[str, str] = {}
    if env_file is not None and env_file.is_file():
        file_vals = parse_env_file(env_file)

    existing_vals: dict[str, str] = {}
    if existing_out is not None and existing_out.is_file():
        try:
            parsed = json.loads(existing_out.read_text(encoding="utf-8"))
            if isinstance(parsed, dict):
                for key in OPTIONAL_KEYS:
                    raw = parsed.get(key)
                    if isinstance(raw, str) and raw.strip():
                        existing_vals[key] = raw.strip()
        except json.JSONDecodeError:
            pass

    merged: dict[str, str] = {}
    for key in ALLOWED_KEYS:
        v = (
            file_vals.get(key)
            or os.environ.get(key, "")
            or existing_vals.get(key, "")
        ).strip()
        if v:
            merged[key] = v
    for url_key in ("SUPABASE_URL", "WEB_BASE_URL", "WEB_ARCHIVE_BASE_URL"):
        if url_key in merged:
            merged[url_key] = _normalize_https_dup_scheme(merged[url_key])
    if "USE_POLYGON_NOTARIZER" not in merged:
        merged["USE_POLYGON_NOTARIZER"] = "true"
    if "APP_ENVIRONMENT" not in merged:
        merged["APP_ENVIRONMENT"] = "production"
    if "WEB_BASE_URL" not in merged:
        merged["WEB_BASE_URL"] = "https://factlockcam.pages.dev"
    if "WEB_ARCHIVE_BASE_URL" not in merged:
        merged["WEB_ARCHIVE_BASE_URL"] = "https://archive.factlockcam.com"
    return merged


def _dart_string_literal(value: str) -> str:
    return json.dumps(value)


def write_generated_dart_defines(path: Path, merged: dict[str, str]) -> None:
    polygon = merged.get("USE_POLYGON_NOTARIZER", "false").strip().lower()
    use_polygon = polygon in ("1", "true", "yes", "on")
    lines = [
        "// GENERATED by scripts/sync_flutter_dart_defines.sh — do not edit by hand.",
        "// Re-run sync after changing repo-root `.env.local`.",
        "// Values are compile-time fallbacks when `flutter run` omits `--dart-define-from-file`.",
        "",
        "/// Fallback Supabase / app defines when CLI omits `--dart-define`.",
        "abstract final class GeneratedDartDefines {",
        f"  static const supabaseUrl = {_dart_string_literal(merged.get('SUPABASE_URL', ''))};",
        f"  static const supabaseAnonKey = {_dart_string_literal(merged.get('SUPABASE_ANON_KEY', ''))};",
        f"  static const localAnonKey = {_dart_string_literal(merged.get('LOCAL_ANON_KEY', ''))};",
        f"  static const webBaseUrl = {_dart_string_literal(merged.get('WEB_BASE_URL', 'https://factlockcam.pages.dev'))};",
        f"  static const webArchiveBaseUrl = {_dart_string_literal(merged.get('WEB_ARCHIVE_BASE_URL', ''))};",
        f"  static const appEnvironment = {_dart_string_literal(merged.get('APP_ENVIRONMENT', 'production'))};",
        f"  static const supportUrl = {_dart_string_literal(merged.get('SUPPORT_URL', ''))};",
        f"  static const usePolygonNotarizer = {'true' if use_polygon else 'false'};",
        f"  static const polygonRpcUrl = {_dart_string_literal(merged.get('POLYGON_RPC_URL', ''))};",
        "}",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--env-file",
        type=Path,
        default=None,
        help="Optional .env-style file (e.g. repo-root .env.local). Values override empty env.",
    )
    ap.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Output JSON path (e.g. factlockcam_app/dart_defines.json).",
    )
    ap.add_argument(
        "--dart-out",
        type=Path,
        default=None,
        help="Optional generated Dart fallback (e.g. lib/core/config/generated_dart_defines.dart).",
    )
    args = ap.parse_args()

    merged = resolve_values(args.env_file, existing_out=args.out)
    missing = [k for k in REQUIRED_KEYS if k not in merged or not merged[k]]
    if missing:
        src = args.env_file if args.env_file else "environment"
        print(
            f"Missing non-empty values for: {', '.join(missing)} (checked {src} + process env).",
            file=sys.stderr,
        )
        if args.dart_out is not None:
            write_generated_dart_defines(args.dart_out, {})
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        json.dumps(merged, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    if args.dart_out is not None:
        write_generated_dart_defines(args.dart_out, merged)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
